/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzarendeles;

import javax.swing.JOptionPane;

/**
 *
 * @author vikis
 */
public class pizzarendeles extends javax.swing.JFrame {

    /**
     * Creates new form pizzarendeles
     */
    public pizzarendeles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblCim = new javax.swing.JLabel();
        pnlTeszta = new javax.swing.JPanel();
        cmbMeret = new javax.swing.JComboBox<>();
        rbnNormal = new javax.swing.JRadioButton();
        rbnTeljeskiorlesu = new javax.swing.JRadioButton();
        rbnGlutenmentes = new javax.swing.JRadioButton();
        chbSajtosszel = new javax.swing.JCheckBox();
        chbVegan = new javax.swing.JCheckBox();
        pnlFizetes = new javax.swing.JPanel();
        rbnKartya = new javax.swing.JRadioButton();
        rbnKeszpenz = new javax.swing.JRadioButton();
        pnlFeltet = new javax.swing.JPanel();
        chbSonka = new javax.swing.JCheckBox();
        chbSzalami = new javax.swing.JCheckBox();
        chbKolbasz = new javax.swing.JCheckBox();
        chbTonhal = new javax.swing.JCheckBox();
        chbAnanasz = new javax.swing.JCheckBox();
        chbGomba = new javax.swing.JCheckBox();
        chbKukorica = new javax.swing.JCheckBox();
        chbOliva = new javax.swing.JCheckBox();
        pnlElerhetosegek = new javax.swing.JPanel();
        btnTelefon = new javax.swing.JButton();
        btnMunkatarsaink = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        rbnFa = new javax.swing.JRadioButton();
        rbnMuanyag = new javax.swing.JRadioButton();
        txtfSemmi = new javax.swing.JTextField();
        txtf100 = new javax.swing.JTextField();
        lblPizzaKep = new javax.swing.JLabel();
        tgbtnRendeles = new javax.swing.JToggleButton();
        tgbtnMegse = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 0));

        lblCim.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        lblCim.setText("PIZZA MADE BY YOU ");

        pnlTeszta.setBackground(new java.awt.Color(255, 255, 255));
        pnlTeszta.setBorder(javax.swing.BorderFactory.createTitledBorder("Tészta típusa"));

        cmbMeret.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---válasszon méretet---", "26 cm", "32 cm", "40 cm" }));

        buttonGroup1.add(rbnNormal);
        rbnNormal.setText("normál");

        buttonGroup1.add(rbnTeljeskiorlesu);
        rbnTeljeskiorlesu.setText("teljeskiörlésű");
        rbnTeljeskiorlesu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnTeljeskiorlesuActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbnGlutenmentes);
        rbnGlutenmentes.setText("gluténmentes");
        rbnGlutenmentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnGlutenmentesActionPerformed(evt);
            }
        });

        chbSajtosszel.setText("sajtos szél");

        chbVegan.setText("vegán");
        chbVegan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbVeganItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlTesztaLayout = new javax.swing.GroupLayout(pnlTeszta);
        pnlTeszta.setLayout(pnlTesztaLayout);
        pnlTesztaLayout.setHorizontalGroup(
            pnlTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTesztaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbnGlutenmentes)
                    .addComponent(rbnTeljeskiorlesu)
                    .addComponent(rbnNormal)
                    .addGroup(pnlTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTesztaLayout.createSequentialGroup()
                            .addComponent(chbSajtosszel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbVegan))
                        .addComponent(cmbMeret, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTesztaLayout.setVerticalGroup(
            pnlTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTesztaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cmbMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbnNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbnTeljeskiorlesu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbnGlutenmentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbSajtosszel)
                    .addComponent(chbVegan))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlFizetes.setBackground(new java.awt.Color(255, 255, 255));
        pnlFizetes.setBorder(javax.swing.BorderFactory.createTitledBorder("Válassz fizetési módot!"));

        buttonGroup4.add(rbnKartya);
        rbnKartya.setText("Kártyával fizetek!");
        rbnKartya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbnKartyaMouseClicked(evt);
            }
        });

        buttonGroup4.add(rbnKeszpenz);
        rbnKeszpenz.setText("Készpénzzel fizetek!");
        rbnKeszpenz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbnKeszpenzMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlFizetesLayout = new javax.swing.GroupLayout(pnlFizetes);
        pnlFizetes.setLayout(pnlFizetesLayout);
        pnlFizetesLayout.setHorizontalGroup(
            pnlFizetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFizetesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFizetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbnKeszpenz)
                    .addComponent(rbnKartya))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFizetesLayout.setVerticalGroup(
            pnlFizetesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFizetesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbnKartya)
                .addGap(15, 15, 15)
                .addComponent(rbnKeszpenz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFeltet.setBackground(new java.awt.Color(255, 255, 255));
        pnlFeltet.setBorder(javax.swing.BorderFactory.createTitledBorder("Feltétek"));

        chbSonka.setText("sonka");

        chbSzalami.setText("szalámi");

        chbKolbasz.setText("kolbász");

        chbTonhal.setText("tonhal");

        chbAnanasz.setText("ananász");

        chbGomba.setText("gomba");

        chbKukorica.setText("kukorica");

        chbOliva.setText("oliva");

        javax.swing.GroupLayout pnlFeltetLayout = new javax.swing.GroupLayout(pnlFeltet);
        pnlFeltet.setLayout(pnlFeltetLayout);
        pnlFeltetLayout.setHorizontalGroup(
            pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeltetLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbSonka)
                    .addComponent(chbSzalami)
                    .addComponent(chbKolbasz)
                    .addComponent(chbTonhal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbAnanasz)
                    .addComponent(chbGomba)
                    .addComponent(chbKukorica)
                    .addComponent(chbOliva))
                .addGap(14, 14, 14))
        );
        pnlFeltetLayout.setVerticalGroup(
            pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeltetLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFeltetLayout.createSequentialGroup()
                        .addComponent(chbAnanasz)
                        .addGap(20, 20, 20)
                        .addComponent(chbGomba)
                        .addGap(20, 20, 20)
                        .addComponent(chbKukorica)
                        .addGap(20, 20, 20)
                        .addComponent(chbOliva))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFeltetLayout.createSequentialGroup()
                        .addComponent(chbSonka)
                        .addGap(20, 20, 20)
                        .addComponent(chbSzalami)
                        .addGap(20, 20, 20)
                        .addComponent(chbKolbasz)
                        .addGap(20, 20, 20)
                        .addComponent(chbTonhal)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlElerhetosegek.setBackground(new java.awt.Color(255, 255, 255));
        pnlElerhetosegek.setBorder(javax.swing.BorderFactory.createTitledBorder("Elérhetőségeink"));

        btnTelefon.setText("Telefon");
        btnTelefon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTelefonMouseClicked(evt);
            }
        });

        btnMunkatarsaink.setText("Munkatársaink");
        btnMunkatarsaink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMunkatarsainkMouseClicked(evt);
            }
        });

        jLabel1.setText("<html><a href=\"https://www.facebook.com\">Facebook</a></html>\n\n");

        javax.swing.GroupLayout pnlElerhetosegekLayout = new javax.swing.GroupLayout(pnlElerhetosegek);
        pnlElerhetosegek.setLayout(pnlElerhetosegekLayout);
        pnlElerhetosegekLayout.setHorizontalGroup(
            pnlElerhetosegekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElerhetosegekLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlElerhetosegekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMunkatarsaink, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlElerhetosegekLayout.createSequentialGroup()
                        .addComponent(btnTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlElerhetosegekLayout.setVerticalGroup(
            pnlElerhetosegekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElerhetosegekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlElerhetosegekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTelefon)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMunkatarsaink)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Válassz evőeszközt!"));

        buttonGroup3.add(rbnFa);
        rbnFa.setText("fa evőeszköz");
        rbnFa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbnFaItemStateChanged(evt);
            }
        });

        buttonGroup3.add(rbnMuanyag);
        rbnMuanyag.setText("műanyag evőeszköz");

        txtfSemmi.setText("     ---- ");

        txtf100.setText("  +100 ft ");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbnMuanyag)
                    .addComponent(rbnFa))
                .addGap(18, 18, 18)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfSemmi)
                    .addComponent(txtf100))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnFa)
                    .addComponent(txtfSemmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnMuanyag)
                    .addComponent(txtf100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblPizzaKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzarendeles/kepek/Képernyőkép 2023-10-10 132731.png"))); // NOI18N
        lblPizzaKep.setText("jLabel2");

        buttonGroup2.add(tgbtnRendeles);
        tgbtnRendeles.setText("Rendelés");
        tgbtnRendeles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tgbtnRendelesMouseClicked(evt);
            }
        });
        tgbtnRendeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtnRendelesActionPerformed(evt);
            }
        });

        buttonGroup2.add(tgbtnMegse);
        tgbtnMegse.setText("Mégse");
        tgbtnMegse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tgbtnMegseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPizzaKep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pnlElerhetosegek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTeszta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlFizetes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tgbtnRendeles, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tgbtnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlFeltet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCim, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCim)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlFeltet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPizzaKep))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlElerhetosegek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFizetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgbtnRendeles)
                    .addComponent(tgbtnMegse))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnTeljeskiorlesuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnTeljeskiorlesuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnTeljeskiorlesuActionPerformed

    private void rbnGlutenmentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnGlutenmentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnGlutenmentesActionPerformed

    private void btnTelefonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTelefonMouseClicked
     int ikonTipus = JOptionPane.QUESTION_MESSAGE; //       
    JOptionPane.showMessageDialog(rootPane, "Cégünket az alábbi számon érheti el: \n+30 30 111 1111 ", "TELEFONSZÁM", 3);
    }//GEN-LAST:event_btnTelefonMouseClicked

    private void tgbtnMegseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgbtnMegseMouseClicked
       System.exit(0);     
    }//GEN-LAST:event_tgbtnMegseMouseClicked

    private void tgbtnRendelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgbtnRendelesMouseClicked
    //int     ikonTipus = JOptionPane.INFORMATION_MESSAGE; //
    //JOptionPane.showMessageDialog(rootPane, "Rendelését felvettük. \nAz 1-es pultnál veheti át", "RENDELÉS LEADVA", 1);
    }//GEN-LAST:event_tgbtnRendelesMouseClicked

    private void rbnFaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbnFaItemStateChanged
    csere();
    }//GEN-LAST:event_rbnFaItemStateChanged

    private void btnMunkatarsainkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMunkatarsainkMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Manager-Kovács János \nSzakács-Kis Ernő \n Pénztáros- Szabó Anna", "MUNKATÁRSAINK", 1);
    }//GEN-LAST:event_btnMunkatarsainkMouseClicked

    private void rbnKartyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbnKartyaMouseClicked
     JOptionPane.showMessageDialog(rootPane, "Átirányítjuk a kártyatársaság honlapjára", "KÁRTYÁS FIZETÉS", 1);
    }//GEN-LAST:event_rbnKartyaMouseClicked

    private void rbnKeszpenzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbnKeszpenzMouseClicked
     JOptionPane.showMessageDialog(rootPane, "Kérem készítse elő a megefelelő összeget,\nhogy segítse munkatársunkat!", "KÉSZPÉNZES FIZETÉS", 1);
    }//GEN-LAST:event_rbnKeszpenzMouseClicked

    private void chbVeganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbVeganItemStateChanged
    if (chbVegan.isSelected()){
        chbSonka.setEnabled(false);
        chbSzalami.setEnabled(false);
        chbKolbasz.setEnabled(false);
        chbTonhal.setEnabled(false);
    }else{
        chbSonka.setEnabled(true);
        chbSzalami.setEnabled(true);
        chbKolbasz.setEnabled(true);
        chbTonhal.setEnabled(true);
    }
    }//GEN-LAST:event_chbVeganItemStateChanged

    private void tgbtnRendelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtnRendelesActionPerformed
       JOptionPane.showMessageDialog(rootPane, "A pizza ára 1500 forint", "végösszeg", 1);
    }//GEN-LAST:event_tgbtnRendelesActionPerformed

    private void csere() {
        String s = txtfSemmi.getText();
        txtfSemmi.setText(txtf100.getText());
        txtf100.setText(s);
    }
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pizzarendeles().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMunkatarsaink;
    private javax.swing.JButton btnTelefon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox chbAnanasz;
    private javax.swing.JCheckBox chbGomba;
    private javax.swing.JCheckBox chbKolbasz;
    private javax.swing.JCheckBox chbKukorica;
    private javax.swing.JCheckBox chbOliva;
    private javax.swing.JCheckBox chbSajtosszel;
    private javax.swing.JCheckBox chbSonka;
    private javax.swing.JCheckBox chbSzalami;
    private javax.swing.JCheckBox chbTonhal;
    private javax.swing.JCheckBox chbVegan;
    private javax.swing.JComboBox<String> cmbMeret;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCim;
    private javax.swing.JLabel lblPizzaKep;
    private javax.swing.JPanel pnlElerhetosegek;
    private javax.swing.JPanel pnlFeltet;
    private javax.swing.JPanel pnlFizetes;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTeszta;
    private javax.swing.JRadioButton rbnFa;
    private javax.swing.JRadioButton rbnGlutenmentes;
    private javax.swing.JRadioButton rbnKartya;
    private javax.swing.JRadioButton rbnKeszpenz;
    private javax.swing.JRadioButton rbnMuanyag;
    private javax.swing.JRadioButton rbnNormal;
    private javax.swing.JRadioButton rbnTeljeskiorlesu;
    private javax.swing.JToggleButton tgbtnMegse;
    private javax.swing.JToggleButton tgbtnRendeles;
    private javax.swing.JTextField txtf100;
    private javax.swing.JTextField txtfSemmi;
    // End of variables declaration//GEN-END:variables
}
